import 'package:flutter/material.dart';

final textformFillColor = Color(0xffF6F7F9);
final textformColor = Color(0xff6C757D);
final mainBtnColor = Color(0xffAACCFF);
final colorwhite = Colors.white;
final titleColor = Colors.black;
final borderColor = Color(0xffEBEBEB);
final discountTextColor = Colors.orange;
final tabUnselectedColor = Color(0xffADB3BC);
final chatColor = Color(0xff50555C);
final completeColor = Color(0xff3CAE5C);
final colorBlack = Colors.black;
final errorColor = Colors.red;
final starColor = Color(0xffF98600);
final primaryColorCode = Color(-13225886);
final secoundryColorCode = Color(-420841);
final btnColorCode = Color(-13225886);
final btntextcolor2 = Color(0x6759FF);
final scaffoldBackgroundColor = Colors.grey.shade50;
