// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'constant/global_configuration.dart';
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: GlobalConfiguration().getValue('apiKey'),
    appId: GlobalConfiguration().getValue('appIdAndroid'),
    messagingSenderId: GlobalConfiguration().getValue('messagingSenderId'),
    projectId: GlobalConfiguration().getValue('projectId'),
    storageBucket: GlobalConfiguration().getValue('storageBucket'),
    databaseURL: GlobalConfiguration().getValue('databaseURL')
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: GlobalConfiguration().getValue('apiKey'),
    appId: GlobalConfiguration().getValue('appIdIos'),
    messagingSenderId: GlobalConfiguration().getValue('messagingSenderId'),
    projectId: GlobalConfiguration().getValue('projectId'),
    storageBucket: GlobalConfiguration().getValue('storageBucket'),
    databaseURL: GlobalConfiguration().getValue('databaseURL'),
    iosBundleId: 'com.wegroomyou.groom',
  );

}